{{- if not .Values.server.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.server.existingSecret.key | quote }}: {{ .Values.server.password | quote }}
{{- end }}
