apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valheim
resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - statefulset.yaml
images:
  - name: valheim-arm64
    newName: ghcr.io/replace-me/valheim-arm64
    newTag: latest
