apiVersion: v1
kind: Service
metadata:
  name: valheim-headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: valheim
  ports:
    - name: game
      port: 2456
      protocol: UDP
      targetPort: game
---
apiVersion: v1
kind: Service
metadata:
  name: valheim
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: valheim
  ports:
    - name: game
      port: 2456
      protocol: UDP
      targetPort: game
    - name: query
      port: 2457
      protocol: UDP
      targetPort: query
    - name: steam
      port: 2458
      protocol: UDP
      targetPort: steam
